import { chromium, devices } from '/opt/node-tools/node_modules/playwright/index.mjs';
const out = process.argv[2];
const b = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const ctx = await b.newContext({ viewport: { width: 844, height: 390 }, hasTouch: true, isMobile: true, deviceScaleFactor: 1 });
const p = await ctx.newPage();
const logs = [];
p.on('pageerror', (e) => logs.push('PAGEERROR ' + e.message));
await p.goto('http://localhost:8080/index.html');
await p.evaluate(() => localStorage.setItem('oneroaddown.save.v1', JSON.stringify({ firstStartDone: true, owned: ['dusty'], selected: 'dusty', cash: 900, cars: {} })));
await p.goto('http://localhost:8080/index.html?fixed');
await p.waitForFunction(() => document.querySelector('#boot.ready'), null, { timeout: 120000 });
await p.touchscreen.tap(400, 200);
await p.waitForFunction(() => window.__game.state === 'menu', null, { timeout: 30000 });
await p.waitForTimeout(2000);
await p.screenshot({ path: `${out}/m_menu.png` });
await p.tap('[data-a=garage]');
await p.waitForTimeout(5000);
await p.screenshot({ path: `${out}/m_garage.png` });
await p.tap('.gtab[data-t=drive]');
await p.waitForFunction(() => window.__game.run && window.__game.run.active, null, { timeout: 90000 });
await p.waitForTimeout(2000);
await p.screenshot({ path: `${out}/m_run.png` });
console.log(logs.join('\n') || 'no errors');
await b.close();
