// Garage + summary screens.
import { chromium } from '/opt/node-tools/node_modules/playwright/index.mjs';
const out = process.argv[2];
const b = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const p = await b.newPage({ viewport: { width: 1280, height: 720 } });
const logs = [];
p.on('console', (m) => logs.push(m.type() + ': ' + m.text()));
p.on('pageerror', (e) => logs.push('PAGEERROR ' + e.message + ' ' + (e.stack || '').split('\n').slice(0, 3).join(' | ')));
await p.goto('http://localhost:8080/index.html');
await p.evaluate(() => localStorage.setItem('oneroaddown.save.v1', JSON.stringify({ firstStartDone: true, owned: ['rusty'], selected: 'rusty', cash: 9000, cars: {}, best: { m1: 2400 } })));
await p.goto('http://localhost:8080/index.html?fixed');
await p.waitForFunction(() => document.querySelector('#boot.ready'), null, { timeout: 90000 });
await p.keyboard.press('Space');
await p.waitForFunction(() => window.__game.state === 'menu', null, { timeout: 30000 });
await p.waitForTimeout(3000);
await p.screenshot({ path: `${out}/g_menu.png` });
await p.click('[data-a=garage]');
await p.waitForTimeout(6000);
await p.screenshot({ path: `${out}/g_upg.png` });
await p.click('.detail .buy');
await p.waitForTimeout(5000);
await p.screenshot({ path: `${out}/g_bought.png` });
await p.click('.upg[data-c=tires]');
await p.waitForTimeout(4000);
await p.screenshot({ path: `${out}/g_tires.png` });
await p.click('.gtab[data-t=vehicles]');
await p.waitForTimeout(1500);
await p.click('.vrow[data-id=kestrel]');
await p.waitForTimeout(4000);
await p.screenshot({ path: `${out}/g_show.png` });
await p.click('.gtab[data-t=garage]');
await p.waitForTimeout(2500);
await p.screenshot({ path: `${out}/g_levels.png` });
await p.click('.gtab[data-t=drive]');
await p.waitForFunction(() => window.__game.run && window.__game.run.active, null, { timeout: 90000 });
await p.evaluate(() => { const r = window.__game.run; r.maxS = 1830; r.runCash = 420; r.vehicle.hp *= 0.4; r.finish('VEHICLE DESTROYED', 'WRECKED'); });
await p.waitForTimeout(5000);
await p.screenshot({ path: `${out}/g_summary.png` });
console.log(logs.filter((l) => !l.includes('GPU stall')).slice(0, 30).join('\n'));
await b.close();
