#!/usr/bin/env python3
"""Builds the browser version from Web/template.html.

Embeds the question packs from Assets/GuessTheAnswer/Resources/GTA/Data and the UI icons as SVG paths
extracted from Material Symbols Rounded (Apache 2.0). Writes:
  Web/guess-the-answer.html      Claude artifact build (online play through artifact rooms)
  Web/crazygames/index.html      CrazyGames build (SDK + the game server at --server-url)
  WebServer/public/index.html    the page the game server hosts itself (connects back to its own host)
  WebServer/game-core.js         rules engine + questions for the server (same code the page runs)
Usage: python3 Tools/build_web.py <MaterialSymbolsRounded[...].ttf> <codepoints> [--server-url wss://host/ws]
"""
import json, os, sys
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont
from fontTools.pens.svgPathPen import SVGPathPen

ROOT = os.path.join(os.path.dirname(__file__), "..")
DATA = os.path.join(ROOT, "Assets", "GuessTheAnswer", "Resources", "GTA", "Data")
ICONS = ["add", "arrow_back", "backspace", "bolt", "check", "close", "content_copy", "contrast", "crown", "front_hand",
         "groups", "how_to_vote", "local_fire_department", "location_city", "lock", "login", "logout", "menu", "more_time",
         "movie", "nutrition", "person", "play_arrow", "public", "refresh", "search", "sentiment_very_satisfied", "settings",
         "smart_toy", "sports_soccer", "star", "swap_horiz", "volume_off", "volume_up", "casino", "help"]

def icons(font_path, cp_path):
    cps = {}
    for line in open(cp_path, encoding="utf-8"):
        p = line.split()
        if len(p) == 2: cps[p[0]] = int(p[1], 16)
    font = instantiateVariableFont(TTFont(font_path), {"FILL": 1, "GRAD": 0, "opsz": 24, "wght": 600})
    cmap = font.getBestCmap(); gs = font.getGlyphSet()
    out = {}
    for n in ICONS:
        pen = SVGPathPen(gs)
        gs[cmap[cps[n]]].draw(pen)
        out[n] = pen.getCommands()
    return out

def questions():
    cat = json.load(open(os.path.join(DATA, "categories.json"), encoding="utf-8"))["categories"]
    qs = []
    lv = {"easy": 0, "normal": 1, "hard": 2, "expert": 2}
    for c in cat:
        if not c.get("pack"): continue
        pack = json.load(open(os.path.join(DATA, c["pack"] + ".json"), encoding="utf-8"))
        for q in pack["questions"]:
            qs.append([q["id"], c["id"], lv.get(q.get("difficulty", "normal"), 1), q["questionText"], q["answers"],
                       q["correctAnswerIndex"], 1 if q.get("keepOrder") else 0, q.get("optionalExplanation") or ""])
    cats = [{"id": c["id"], "name": c["name"], "icon": c["icon"], "color": c["color"], "classic": c.get("includeInClassic", True)} for c in cat]
    return cats, qs

DEFAULT_SERVER = "wss://gta-quiz-llossau.onrender.com/ws"
CG_SDK = '<script src="https://sdk.crazygames.com/crazygames-sdk-v3.js"></script>\n'

def page(body, cfg, head=""):
    """A standalone page: the template plus the document skeleton the artifact host would add."""
    body = body.replace("/*@@CFG@@*/{}", json.dumps(cfg, separators=(",", ":")))
    return ('<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n'
            '<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">\n' + head + body + "\n</html>\n")

def write(rel, text):
    path = os.path.join(ROOT, *rel.split("/"))
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, "w", encoding="utf-8").write(text)
    print("wrote", rel, len(text) // 1024, "KB")

def core(tpl, data):
    """Everything the server needs from the page script: helpers, avatars, Deck, Engine and Room."""
    script = tpl.split("<script>\n", 1)[1].split("/*@@CORE_END@@*/", 1)[0]
    return ("// Generated by Tools/build_web.py from Web/template.html. Do not edit.\n\"use strict\";\n"
            + script.replace("/*@@DATA@@*/", data)
            + "\nmodule.exports = { CATS, QS, CAT, RULES, PH, RK, END, Engine, Room, genCode, cleanName, normAv, rnd, ri, CODE_ABC };\n")

def main():
    args = sys.argv[1:]
    server = DEFAULT_SERVER
    if "--server-url" in args:
        i = args.index("--server-url"); server = args[i + 1]; del args[i:i + 2]
    ic = icons(args[0], args[1])
    cats, qs = questions()
    tpl = open(os.path.join(ROOT, "Web", "template.html"), encoding="utf-8").read()
    data = "const CATS=" + json.dumps(cats, ensure_ascii=False, separators=(",", ":")) + ";\nconst QS=" + \
        json.dumps(qs, ensure_ascii=False, separators=(",", ":")) + ";\nconst ICONS=" + json.dumps(ic, separators=(",", ":")) + ";"
    out = tpl.replace("/*@@DATA@@*/", data)
    write("Web/guess-the-answer.html", out)
    write("Web/crazygames/index.html", page(out, {"server": server, "cg": True}, CG_SDK))
    write("WebServer/public/index.html", page(out, {"server": "auto"}))
    write("WebServer/game-core.js", core(tpl, data))
    print(len(qs), "questions,", len(ic), "icons, server", server)

if __name__ == "__main__":
    main()
