"use strict";
// Game server for the browser version. It runs the page's own Room/Engine code (game-core.js, generated by
// Tools/build_web.py) as the single authority: players send intents, the server sends every player in a room
// the same compact snapshots the page renders. It also does public matchmaking and hosts the game page itself.
//
//   client → server  hello {pid,key,name,av} · profile {name,av} · create · join {code} · leave · act {k,v}
//                    queue {mode} · unqueue · emo {e}
//   server → client  hi {n} · n {n} · reset · s {r,m} · err {code} · left {why} · q {found,need,ex} · found · emo {pid,e}

const http = require("http");
const fs = require("fs");
const path = require("path");
const { WebSocketServer } = require("ws");
const core = require("./game-core.js");

const { Room, genCode, cleanName, normAv, CAT } = core;
const PORT = +process.env.PORT || 8080;
const MAX_PLAYERS = +process.env.MAX_PLAYERS || 2000;
const MAX_MSG = 4096, MSGS_PER_SEC = 30, EMOTE_GAP = 600, EXPAND_MS = 30000, PUBLIC_START = 4.5;
const ACTIONS = new Set(["ready", "team", "move", "settings", "addbot", "rmbot", "start", "answer", "joker", "vote", "steal", "skip", "rematch", "lobby"]);

const now = () => performance.now() / 1000;
const log = (...a) => console.log(new Date().toISOString().slice(11, 19), ...a);

/** pid → { pid, key, ws, name, av, code, queue: {mode, since} | null, goneAt, emoAt } */
const players = new Map();
/** code → { room, res } */
const rooms = new Map();

// ───────────────────────── HTTP: the game page and a health check ─────────────────────────
const PAGE = path.join(__dirname, "public", "index.html");
const server = http.createServer((req, res) => {
  const url = (req.url || "/").split("?")[0];
  if (url === "/health") {
    res.writeHead(200, { "content-type": "application/json", "cache-control": "no-store" });
    res.end(JSON.stringify({ status: "ok", players: online(), rooms: rooms.size }));
    return;
  }
  if (url === "/" || url === "/index.html") {
    fs.readFile(PAGE, (err, buf) => {
      if (err) { res.writeHead(404); res.end("Game page missing. Run Tools/build_web.py."); return; }
      res.writeHead(200, { "content-type": "text/html; charset=utf-8", "cache-control": "no-cache" });
      res.end(buf);
    });
    return;
  }
  res.writeHead(404, { "content-type": "text/plain" });
  res.end("Not found");
});

// ───────────────────────── WebSocket ─────────────────────────
const wss = new WebSocketServer({ server, path: "/ws", maxPayload: MAX_MSG });

wss.on("connection", ws => {
  ws.alive = true; ws.pid = null; ws.win = Date.now(); ws.count = 0;
  ws.on("pong", () => { ws.alive = true; });
  ws.on("message", (data, binary) => {
    if (binary) return;
    const t = Date.now();
    if (t - ws.win > 1000) { ws.win = t; ws.count = 0; }
    if (++ws.count > MSGS_PER_SEC) return;
    let m; try { m = JSON.parse(data.toString()); } catch (e) { return; }
    if (!m || typeof m.t !== "string") return;
    try { handle(ws, m); } catch (e) { log("error handling", m.t, e && e.stack || e); }
  });
  ws.on("close", () => disconnected(ws));
  ws.on("error", () => { });
});

function send(ws, msg) { if (ws && ws.readyState === 1) ws.send(typeof msg === "string" ? msg : JSON.stringify(msg)); }
function online() { let n = 0; for (const p of players.values()) if (p.ws) n++; return n; }

function handle(ws, m) {
  if (m.t === "hello") return hello(ws, m);
  const p = ws.pid && players.get(ws.pid);
  if (!p || p.ws !== ws) return;
  switch (m.t) {
    case "profile": {
      p.name = cleanName(m.name); p.av = normAv(m.av);
      const rr = p.code && rooms.get(p.code), mem = rr && rr.room.find(p.pid);
      if (mem && rr.room.st === 0) { mem.name = p.name; mem.av = p.av; rr.room.dirty = true; }
      break;
    }
    case "create": {
      leaveRoom(p);
      const code = newCode();
      const room = new Room(code, {}, {});
      rooms.set(code, { room, res: 0 });
      room.join(p.pid, p.name, p.av, now());
      p.code = code; p.queue = null;
      flush(code);
      break;
    }
    case "join": {
      const code = String(m.code || "").toUpperCase();
      if (!/^[A-Z0-9]{6}$/.test(code)) return send(ws, { t: "err", code: "INVALID_CODE" });
      const rr = rooms.get(code);
      if (!rr) return send(ws, { t: "err", code: "ROOM_NOT_FOUND" });
      if (rr.room.find(p.pid)) { rr.room.setConn(p.pid, true, now()); p.code = code; flush(code, true); return; }
      leaveRoom(p); p.queue = null;
      const err = rr.room.join(p.pid, p.name, p.av, now());
      if (err) return send(ws, { t: "err", code: err });
      p.code = code;
      flush(code);
      break;
    }
    case "leave": leaveRoom(p); p.queue = null; break;
    case "act": {
      const rr = p.code && rooms.get(p.code);
      if (!rr) return send(ws, { t: "err", code: "NOT_IN_ROOM" });
      const k = String(m.k);
      if (!ACTIONS.has(k)) return send(ws, { t: "err", code: "BAD_REQUEST" });
      const err = rr.room.apply(p.pid, k, cleanValue(k, m.v), now());
      if (err) send(ws, { t: "err", code: err });
      flush(p.code);
      break;
    }
    case "queue": {
      const mode = m.mode === "2v2" ? "2v2" : "1v1";
      leaveRoom(p);
      p.queue = { mode, since: Date.now() };
      matchmake();
      break;
    }
    case "unqueue": p.queue = null; break;
    case "emo": {
      const e = m.e | 0, t = Date.now();
      if (e < 0 || e > 5 || t - (p.emoAt || 0) < EMOTE_GAP || !p.code) return;
      p.emoAt = t;
      toRoom(p.code, { t: "emo", pid: p.pid, e }, p.pid);
      break;
    }
  }
}

/** Only pass on values the rules engine expects; settings keep their known keys only. */
function cleanValue(k, v) {
  if (k === "settings") {
    const s = {}; if (!v || typeof v !== "object") return s;
    for (const key of ["rounds", "answerTime", "difficulty", "teamMode"]) if (key in v) s[key] = +v[key];
    if (typeof v.category === "string" && CAT[v.category]) s.category = v.category;
    return s;
  }
  if (typeof v === "number" || typeof v === "boolean") return v;
  if (typeof v === "string") return v.slice(0, 48);
  return null;
}

function hello(ws, m) {
  const pid = String(m.pid || ""), key = String(m.key || "");
  if (!/^[A-Za-z0-9]{4,24}$/.test(pid) || key.length < 8 || key.length > 64) { ws.close(); return; }
  let p = players.get(pid);
  if (p && p.key !== key) { send(ws, { t: "reset" }); return; }
  if (!p) {
    if (online() >= MAX_PLAYERS) { send(ws, { t: "err", code: "BUSY" }); ws.close(); return; }
    p = { pid, key, ws: null, name: "", av: null, code: null, queue: null, goneAt: 0, emoAt: 0 };
    players.set(pid, p);
  }
  if (p.ws && p.ws !== ws) { const old = p.ws; old.pid = null; try { old.close(); } catch (e) { } }
  if (ws.pid && ws.pid !== pid) disconnected(ws);
  p.ws = ws; ws.pid = pid; p.goneAt = 0;
  p.name = cleanName(m.name); p.av = normAv(m.av);
  send(ws, { t: "hi", n: online() });
  // Back after a dropped connection or a reload: straight into the room if it still holds us.
  if (p.code) {
    const rr = rooms.get(p.code);
    if (rr && rr.room.find(pid)) { rr.room.setConn(pid, true, now()); flush(p.code, true); }
    else { p.code = null; send(ws, { t: "left", why: "timeout" }); }
  }
}

function disconnected(ws) {
  const p = ws.pid && players.get(ws.pid);
  ws.pid = null;
  if (!p || p.ws !== ws) return;
  p.ws = null; p.queue = null; p.goneAt = Date.now();
  const rr = p.code && rooms.get(p.code);
  if (rr) { rr.room.setConn(p.pid, false, now()); flush(p.code); }
}

function leaveRoom(p) {
  const code = p.code; if (!code) return;
  p.code = null;
  const rr = rooms.get(code); if (!rr) return;
  rr.room.leave(p.pid, now());
  flush(code);
}

function newCode() { let c; do c = genCode(); while (rooms.has(c)); return c; }

/** Sends the room's snapshot to everyone in it (only when something changed, unless forced). */
function flush(code, force) {
  const rr = rooms.get(code); if (!rr) return;
  const room = rr.room, e = room.eng;
  if (!force && !room.dirty && !(e && e.dirty)) return;
  const t = now();
  room.dirty = false; if (e) e.dirty = false;
  const msg = JSON.stringify({ t: "s", r: room.snapR(t), m: e ? e.snap(t) : null });
  for (const m of room.M) { if (m.bot) continue; const p = players.get(m.id); if (p && p.code === code) send(p.ws, msg); }
  if (e && e.res && e.res.sq !== rr.res) { rr.res = e.res.sq; botEmotes(code, e); }
}

function toRoom(code, msg, except) {
  const rr = rooms.get(code); if (!rr) return;
  const text = JSON.stringify(msg);
  for (const m of rr.room.M) { if (m.bot || m.id === except) continue; const p = players.get(m.id); if (p && p.code === code) send(p.ws, text); }
}

/** Bots react to a result with an emote now and then, like they do in practice. */
function botEmotes(code, e) {
  const res = e.res; if (!res || !res.k) return;
  for (const b of e.P) {
    if (!b.bot || Math.random() > 0.28) continue;
    const mine = b.team === res.t, good = res.ok, pick = a => a[Math.floor(Math.random() * a.length)];
    const emo = good ? (mine ? pick([1, 5, 3]) : pick([2, 4])) : (mine ? pick([2, 4]) : pick([0, 5]));
    setTimeout(() => toRoom(code, { t: "emo", pid: b.id, e: emo }), 300 + Math.random() * 900);
  }
}

// ───────────────────────── Matchmaking ─────────────────────────
function matchmake() {
  const t = Date.now();
  const waiting = () => [...players.values()].filter(p => p.queue && p.ws).sort((a, b) => a.queue.since - b.queue.since);
  const expanded = p => t - p.queue.since > EXPAND_MS;

  let duo = waiting().filter(p => p.queue.mode === "2v2");
  while (duo.length >= 4) startPublic(duo.splice(0, 4), 4);
  // A long 2v2 wait with three people: start and let a bot take the fourth seat.
  if (duo.length === 3 && duo.every(expanded)) startPublic(duo.splice(0, 3), 4);

  let solo = waiting().filter(p => p.queue.mode === "1v1" || expanded(p));
  while (solo.length >= 2) startPublic(solo.splice(0, 2), 2);

  const left = waiting();
  const n2 = left.filter(p => p.queue.mode === "2v2").length, n1 = left.filter(p => p.queue.mode === "1v1" || expanded(p)).length;
  for (const p of left) {
    const two = p.queue.mode === "2v2";
    send(p.ws, { t: "q", found: Math.max(1, two ? Math.min(4, n2) : Math.min(2, n1)), need: two ? 4 : 2, ex: two && expanded(p) });
  }
}

function startPublic(list, need) {
  const code = newCode();
  const room = new Room(code, { pub: true }, { rounds: 5, teamMode: need === 4 ? 2 : 1 });
  rooms.set(code, { room, res: 0 });
  const t = now();
  for (const p of list) {
    p.queue = null; leaveRoom(p);
    room.join(p.pid, p.name, p.av, t);
    p.code = code;
    send(p.ws, { t: "found" });
  }
  room.need = need; room.autoAt = t + PUBLIC_START;
  flush(code, true);
  log("public match", code, list.length + "/" + need);
}

// ───────────────────────── Ticks ─────────────────────────
setInterval(() => {
  const t = now();
  for (const [code, rr] of rooms) {
    const room = rr.room;
    const before = new Set(room.M.map(m => m.id));
    try { room.tick(t); } catch (e) { log("room tick failed", code, e && e.stack || e); }
    // Players the room let go of (gone longer than the grace period) are no longer in it.
    for (const id of before) if (!room.find(id)) { const p = players.get(id); if (p && p.code === code) { p.code = null; send(p.ws, { t: "left", why: "timeout" }); } }
    if (!room.M.some(m => !m.bot)) { rooms.delete(code); continue; }
    flush(code);
  }
}, 100);

setInterval(matchmake, 1000);

setInterval(() => {
  // Heartbeat: drop dead sockets so their players count as disconnected.
  for (const ws of wss.clients) { if (!ws.alive) { ws.terminate(); continue; } ws.alive = false; try { ws.ping(); } catch (e) { } }
  // Forget players who are long gone and not in a room.
  const t = Date.now();
  for (const [pid, p] of players) if (!p.ws && !p.code && t - p.goneAt > 10 * 60 * 1000) players.delete(pid);
  const n = JSON.stringify({ t: "n", n: online() });
  for (const p of players.values()) if (p.ws && !p.code) send(p.ws, n);
}, 15000);

server.listen(PORT, () => log("Guess the Answer server on port", PORT, "·", core.QS.length, "questions"));

module.exports = { server, rooms, players };
