// skips the intro, plays the tutorial by driving the same calls the input would trigger
export default async ({ step, snap, ev, page, until }) => {
  await step(0.5);
  await ev(() => { window.__game.newGame(); });
  await until(() => window.__game.state === 'intro');
  await step(1);
  await ev(() => { window.__game.skipPointer = true; });
  await until(() => window.__game.state === 'play');
  await ev(() => { window.__game.skipPointer = false; });
  await step(1);
  await snap('after_intro');
  // wait for the customer
  await step(7);
  await snap('customer_enters');
  await until(() => window.__game.customers.list[0]?.state === 'waitingTalk');
  await step(1);
  const look = () => ev(() => { const g = window.__game; const c = g.customers.list[0]; if (!c) return 'nocust'; const p = c.headPos(); g.player.lookTowards(p, 1, 50); g.player.applyCamera(0); return c.state; });
  console.log('state', await look());
  await step(0.3);
  await snap('talk_prompt');
  await ev(() => { window.__game.input.press('interact'); });
  await step(2);
  await snap('request');
  await step(4);
  // chair
  await ev(() => { const g = window.__game; g.player.place({ x: -0.2, z: 0.2 }, 0.6, -0.2); g.player.lookTowards(new (g.camera.position.constructor)(-0.9, 1.0, -1.45), 1, 50); g.player.applyCamera(0); });
  await step(0.3);
  await snap('chair_prompt');
  await ev(() => { window.__game.input.press('interact'); });
  await step(7);
  await snap('seated');
  // cape
  await ev(() => { const g = window.__game; g.player.lookTowards(new (g.camera.position.constructor)(-2.05, 1.5, -2.56), 1, 50); g.player.applyCamera(0); });
  await step(0.3);
  await snap('cape_prompt');
  await ev(() => { window.__game.input.press('interact'); });
  await step(0.9);
  await snap('cape_throw');
  await until(() => window.__game.state === 'barber');
  await step(1.5);
  await snap('barber_mode');
  await step(3);
  // pick up clippers, power
  await ev(() => window.__game.barber.selectTool('clipper'));
  await step(2);
  await ev(() => window.__game.barber.togglePower());
  await step(1.5);
  await snap('clipper_on');
  // cut the right side by aiming the pointer at the head
  const cutRegion = async (phiFrom, phiTo, thFrom, thTo, secs) => {
    const steps = Math.round(secs * 30);
    for (let i = 0; i < steps; i++) {
      await ev(([i, steps, phiFrom, phiTo, thFrom, thTo]) => {
        const g = window.__game, c = g.barber.c;
        const k = i / steps;
        const rows = 5;
        const row = Math.floor(k * rows), kk = (k * rows) % 1;
        const phi = phiFrom + (phiTo - phiFrom) * (row % 2 ? 1 - kk : kk);
        const th = thFrom + (thTo - thFrom) * (row / (rows - 1));
        const p = c.hair.surfacePoint(phi, th, 0.01).project(g.camera);
        g.input.pointer.x = p.x; g.input.pointer.y = p.y; g.input.pointer.down = true;
      }, [i, steps, phiFrom, phiTo, thFrom, thTo]);
      await step(1 / 30);
    }
    await ev(() => { window.__game.input.pointer.down = false; });
  };
  await ev(() => { window.__game.setChairAngle(-1.4, 3); });
  await step(1.5);
  await cutRegion(-2.3, -0.75, 1.0, 1.75, 6);
  await snap('right_cut');
  await step(2);
  await ev(() => { window.__game.setChairAngle(1.5, 3); });
  await step(1.5);
  await cutRegion(0.75, 2.3, 1.0, 1.75, 6);
  await snap('left_cut');
  await ev(() => { window.__game.setChairAngle(0, 3); });
  await step(1.5);
  await cutRegion(2.3, 3.14, 1.0, 2.1, 4);
  await cutRegion(-3.14, -2.3, 1.0, 2.1, 4);
  await snap('back_cut');
  await step(2);
  await ev(() => window.__game.barber.selectTool('scissors'));
  await ev(() => { const b = window.__game.barber; b.camPitch = 1.0; window.__game.setChairAngle(Math.PI, 3); });
  await step(1.5);
  await cutRegion(-1.3, 1.3, 0.05, 0.85, 12);
  await cutRegion(-1.3, 1.3, 0.05, 0.85, 8);
  await ev(() => { window.__game.setChairAngle(0, 3); });
  await step(1.5);
  await cutRegion(-0.5, 0.5, 0.55, 0.8, 3);
  await ev(() => { window.__game.barber.camPitch = 0.3; });
  await snap('top_cut');
  await step(1);
  await until(() => !window.__game.barber.lockTools, 20);
  await ev(() => window.__game.barber.selectTool('trimmer'));
  await ev(() => { const b = window.__game.barber; if (!b.power) b.togglePower(); });
  await ev(() => { window.__game.setChairAngle(0, 3); window.__game.barber.camPitch = -0.1; });
  await step(1.5);
  await cutRegion(1.6, 3.14, 2.15, 2.42, 6);
  await cutRegion(-3.14, -1.6, 2.15, 2.42, 6);
  await ev(() => { window.__game.setChairAngle(1.5, 3); });
  await step(1);
  await cutRegion(0.9, 1.4, 1.6, 2.1, 3);
  await ev(() => { window.__game.setChairAngle(-1.5, 3); });
  await step(1);
  await cutRegion(-1.4, -0.9, 1.6, 2.1, 3);
  await snap('edges');
  console.log(await ev(() => JSON.stringify(window.__game.barber.stats, (k, v) => typeof v === 'number' ? +v.toFixed(3) : v)));
  await step(2);
  await ev(() => window.__game.barber.requestFinish());
  await step(2);
  await snap('mirror1');
  await step(3);
  await snap('mirror2');
  await step(3);
  await snap('result');
  await step(6);
  await snap('result2');
  await page.evaluate(() => document.querySelector('.cbtn')?.click());
  await step(4);
  await snap('pay');
  await step(4);
  await snap('leave');
  await step(8);
  await snap('upgrade_obj');
  await ev(() => window.__game.openUpgrades());
  await step(1);
  await snap('upgrades_panel');
  await ev(() => window.__game.buy('bulb'));
  await step(1);
  await ev(() => window.__game.ui.closePanel());
  await step(3);
  await snap('new_light');
  await step(8);
  await snap('day1');
  console.log(await ev(() => JSON.stringify({ st: window.__game.state, money: window.__game.money, lvl: window.__game.level, owned: window.__game.save.owned })));
};
